import { FORM_FIELDS_TYPE } from "../validation/helper/fields.js";
import { OPERATORS } from "../validation/helper/operators.js";
import { FIELDS_PROPS as FPs } from "../validation/helper/fields.js";

const checkboxOptions = [
  { label: "React", value: "react", help: "Most used" },
  { label: "Vue", value: "vue", help: "Gaining popularity" },
  { label: "Angular", value: "angular", disabled: true, help: "Not preferred" },
];

const radioOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
  {
    label: "Other",
    value: "other",
    disabled: true,
    help: "Currently unavailable",
  },
];

export const configData07 = {
  [FPs.TITLE]: "All Fields Test Form",
  [FPs.DESCRIPTION]: "Test form including all field types for quick validation",
  [FPs.ENDPOINT]: "http://localhost:4320/public/dev/schedule-meeting",
  [FPs.MODE]: "single",
  [FPs.FIELDS]: [
    {
      [FPs.NAME]: "textField",
      [FPs.TYPE]: FORM_FIELDS_TYPE.TEXT,
      [FPs.LABEL]: "Text Field",
      [FPs.PLACEHOLDER]: "Enter text",
      [FPs.REQUIRED]: true,
      [FPs.MIN_LENGTH]: 2,
      [FPs.MAX_LENGTH]: 20,
    },
    {
      [FPs.NAME]: "textArea",
      [FPs.TYPE]: FORM_FIELDS_TYPE.TEXT_AREA,
      [FPs.LABEL]: "Text Area",
      [FPs.PLACEHOLDER]: "Enter more text",
      [FPs.REQUIRED]: false,
      [FPs.MIN_LENGTH]: 5,
      [FPs.MAX_LENGTH]: 200,
    },
    {
      [FPs.NAME]: "email",
      [FPs.TYPE]: FORM_FIELDS_TYPE.EMAIL,
      [FPs.LABEL]: "Email Address",
      [FPs.PLACEHOLDER]: "Enter email",
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "mobile",
      [FPs.TYPE]: FORM_FIELDS_TYPE.MOBILE,
      [FPs.LABEL]: "Mobile Number",
      [FPs.CODE]: "+91",
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "password",
      [FPs.TYPE]: FORM_FIELDS_TYPE.PASSWORD,
      [FPs.LABEL]: "Password",
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "date",
      [FPs.TYPE]: FORM_FIELDS_TYPE.DATE,
      [FPs.LABEL]: "Date Picker",
      [FPs.MODE]: "month-year",
      [FPs.REQUIRED]: true,
      [FPs.RESTRICTION_START_DATE]: "01-01-2020",
      [FPs.RESTRICTION_END_DATE]: "31-12-2030",
    },
    {
      [FPs.NAME]: "time",
      [FPs.TYPE]: FORM_FIELDS_TYPE.TIME,
      [FPs.LABEL]: "Time Picker",
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "address",
      [FPs.TYPE]: FORM_FIELDS_TYPE.ADDRESS,
      [FPs.LABEL]: "Address",
      [FPs.REQUIRED]: false,
      [FPs.IS_HOUSE]: true,
      [FPs.IS_STREET]: true,
      [FPs.IS_CITY]: true,
      [FPs.IS_STATE]: true,
      [FPs.IS_POSTAL]: true,
      [FPs.IS_COUNTRY]: true,
      [FPs.IS_LANDMARK]: true,
    },
    {
      [FPs.NAME]: "dropdown",
      [FPs.TYPE]: FORM_FIELDS_TYPE.DROPDOWN,
      [FPs.LABEL]: "Dropdown",
      [FPs.REQUIRED]: true,
      [FPs.OPTIONS]: ["Option 1", "Option 2"],
    },
    {
      [FPs.NAME]: "multiDropdown",
      [FPs.TYPE]: FORM_FIELDS_TYPE.MULTI_DROPDOWN,
      [FPs.LABEL]: "Multi Dropdown",
      [FPs.OPTIONS]: ["A", "B", "C"],
    },
    {
      [FPs.NAME]: "checkbox",
      [FPs.TYPE]: FORM_FIELDS_TYPE.CHECKBOX,
      [FPs.LABEL]: "Checkbox Group",
      [FPs.OPTIONS]: checkboxOptions,
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "radio",
      [FPs.TYPE]: FORM_FIELDS_TYPE.RADIO,
      [FPs.LABEL]: "Radio Group",
      [FPs.OPTIONS]: radioOptions,
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "switch",
      [FPs.TYPE]: FORM_FIELDS_TYPE.SWITCH,
      [FPs.LABEL]: "Switch Field",
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "color",
      [FPs.TYPE]: FORM_FIELDS_TYPE.COLOR,
      [FPs.LABEL]: "Color Picker",
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "slider",
      [FPs.TYPE]: FORM_FIELDS_TYPE.SLIDER,
      [FPs.LABEL]: "Slider",
      [FPs.MIN]: 0,
      [FPs.MAX]: 100,
      [FPs.STEP]: 5,
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "stepper",
      [FPs.TYPE]: FORM_FIELDS_TYPE.STEPPER,
      [FPs.LABEL]: "Stepper",
      [FPs.MIN]: 0,
      [FPs.MAX]: 10,
      [FPs.STEP]: 1,
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "search",
      [FPs.TYPE]: FORM_FIELDS_TYPE.SEARCH,
      [FPs.LABEL]: "Search Box",
      [FPs.OPTIONS]: ["Apple", "Banana", "Orange"],
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "json",
      [FPs.TYPE]: FORM_FIELDS_TYPE.JSON,
      [FPs.LABEL]: "JSON Field",
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "file",
      [FPs.TYPE]: FORM_FIELDS_TYPE.FILE,
      [FPs.LABEL]: "File Upload",
      [FPs.MULTIPLE]: true,
      [FPs.MAX_FILES]: 3,
      [FPs.MAX_SIZE_MB]: 20,
      [FPs.ALLOWED_TYPES]: ["application/pdf"],
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "audio",
      [FPs.TYPE]: FORM_FIELDS_TYPE.AUDIO,
      [FPs.LABEL]: "Audio Upload",
      [FPs.MAX_SIZE_MB]: 50,
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "image",
      [FPs.TYPE]: FORM_FIELDS_TYPE.IMAGE,
      [FPs.LABEL]: "Image Upload",
      [FPs.MAX_SIZE_MB]: 5,
      [FPs.REQUIRE_SQUARE]: false,
      [FPs.REQUIRED]: false,
    },
    {
      [FPs.NAME]: "video",
      [FPs.TYPE]: FORM_FIELDS_TYPE.VIDEO,
      [FPs.LABEL]: "Video Upload",
      [FPs.MAX_SIZE_MB]: 100,
      [FPs.PREVIEW]: true,
      [FPs.REQUIRED]: false,
    },
    // { [FPs.NAME]: "otp", [FPs.TYPE]: FORM_FIELDS_TYPE.OTP, [FPs.LABEL]: "OTP Field", [FPs.USER_ID]: "dvfgvdv", [FPs.LENGTH]: 6, [FPs.IS_NUMERIC]: true, [FPs.REQUIRED]: true },
    {
      [FPs.NAME]: "securityQuestion",
      [FPs.TYPE]: FORM_FIELDS_TYPE.SECURTY_QUESTION,
      [FPs.LABEL]: "Security Question",
      [FPs.OPTIONS]: ["Que1", "Que2", "Que3"],
      [FPs.REQUIRED]: true,
    },
    {
      [FPs.NAME]: "repeatableGroup",
      [FPs.LABEL]: "Repeatable Example",
      [FPs.REPEATABLE]: true,
      [FPs.MORE_LABEL]: "More",
      [FPs.FIELDS]: [
        {
          [FPs.NAME]: "field1",
          [FPs.TYPE]: FORM_FIELDS_TYPE.TEXT,
          [FPs.LABEL]: "Inner Field",
        },
      ],
    },
  ],
};
