export const FORM_FIELDS_TYPE = {
  DROPDOWN: "dropdown",
  MULTI_DROPDOWN: "multi-dropdown",
  EMAIL: "email",
  PASSWORD: "password",
  MOBILE: "mobile",
  DATE: "date",
  TIME: "time",
  ADDRESS: "address",
  TEXT: "text",
  TEXT_AREA: "textArea",
  JSON: "json",
  FILE: "file",
  AUDIO: "audio",
  VIDEO: "video",
  IMAGE: "image",
  SECURTY_QUESTION: "secrityuQuestion",
  OTP: "otp",
  CHECKBOX: "checkbox",
  COLOR: "color",
  RADIO: "radio",
  SEARCH: "search",
  SWITCH: "switch",
  SLIDER: "slider",
  STEPPER: "stepper",
};
